#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if there are tests containing `.only`
bash scripts/searchTestsForOnly.bash

# run the tests of the utils or tests that have been modifeid
bash scripts/runTestsForChangedUtils.bash
